#!/usr/bin/perl -w

use strict;

use CGI qw(-no_xhtml);
use DBI;
use Encode;
use POSIX ();
use URI;
use Manx::DB;
use Manx::User;
use Manx::Utilities;

binmode STDOUT, ':utf8';

my $q = CGI->new();

sub html_header($$);
sub undef_empty($);

my ($dbh, $smt, $sth, $rc, $rv, @rowary, $r);

my $SEARCHURL = '/manx/search';
my $DETAILSURL = '/manx/details';

my $DEFAULTNUMPERPAGE = 10;

my @errors;

$dbh = connectdb();
die $DBI::errstr if $DBI::err;


my $user = Manx::User::from_session($dbh, $q->cookie('manxSession'));

if (!$user->{logged_in}) {
	$dbh->disconnect;
	# not logged in. use redirect param to get back here
	my $loc = $q->url(-full => 1, -query => 1);
	my $log = URI->new_abs('/manx/login', $loc);
	$log->query_form(redirect => $loc);
	print header(-status => '303 login first', -location => $log, -type => 'text/plain', -charset => 'utf-8');
	exit;
}

@rowary = $dbh->selectrow_array('select confval from CONFIG where confkey="updated"');
my ($year, $mon, $mday, $hour, $min, $sec) = $rowary[0] =~ /(....)(..)(..)(..)(..)(..)/;
my $time = POSIX::mktime($sec, $min, $hour, $mday, $mon - 1, $year - 1900);
my $tlm = POSIX::strftime("%a, %d %b %Y %T GMT", gmtime($time));

#print $q->header(-charset => 'utf-8');
#html_header($user->{logged_in}, $user->{username});

# Add PUBHISTORY row, with ph_pub = 0
# Add PUB row, with pub_history = ph_id
# Update PUBHISTORY row, with ph_pub = pub_id

# Explicit lang default because MySQL moans at putting NULL in now. Hmmph.
undef_empty('lang'); $q->param('lang', '+en') if !defined($q->param('lang'));
undef_empty('pubdate');
undef_empty('part');

$dbh->trace(2);

$rv = $dbh->do('insert into PUBHISTORY (' .
		'ph_created, ph_edited_by, ph_pub, ph_pubtype,' .
		'ph_company, ph_part, ph_alt_part, ph_revision,' .
		'ph_pubdate, ph_title, ph_keywords, ph_notes,' .
		'ph_lang,' .
		'ph_match_part, ph_match_alt_part, ph_sort_part)' . # calculated fields
		' values (now(), ?, 0, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', undef,
	$user->{id},
	scalar $q->param('pt'),
	scalar $q->param('company'),
	scalar $q->param('part'),
	scalar $q->param('altpart'),
	scalar $q->param('revision'),
	scalar $q->param('pubdate'),
	scalar $q->param('title'),
	scalar $q->param('keywords'),
	scalar $q->param('notes'),
	scalar $q->param('lang'),
	normalise_part_number($q->param('part')),
	normalise_part_number($q->param('altpart')),
	sort_part_number($q->param('part'))
);

die $dbh->errstr if !defined($rv);

my $ph_id = $dbh->{mysql_insertid};

$dbh->trace(0);
$rv = $dbh->do('insert into PUB (pub_history) values (?)', undef, $ph_id);

my $pub_id = $dbh->{mysql_insertid};

$rv = $dbh->do('update PUBHISTORY set ph_pub = ? where ph_id = ?', undef, $pub_id, $ph_id);

my $loc = $q->url(-full => 1);
my $det = '/manx/details/' . $q->param('company') . ',' . $pub_id;
my $log = URI->new_abs($det, $loc);
print $q->header(-status => '303 result of adding pub', -location => $log, -type => 'text/plain', -charset => 'utf-8');

$dbh->disconnect() if $dbh;
exit;

sub undef_empty($) {
	my $p = shift;
	$q->delete($p) if (defined($q->param($p)) && $q->param($p) eq '');
}

sub html_header($$) {
	my ($logged_in, $username) = @_;

	print qq{<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n},
		qq{<html lang="en">\n<head>\n<title>Manx</title>\n},
		qq{<link rel="stylesheet" type="text/css" href="manx-style.css">\n},
		qq{<link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">\n},
		qq{<script type="text/javascript" src="jquery-1.3.2.min.js"></script>\n},
		'<script type="text/javascript" src="lookpart.js"></script>',
		qq{</head>\n};

	print qq{<body id="VT100-NET">\n};
	print qq{<div id="AUTH">}, html_encode($username), ' | ';
	if ($logged_in) {
		print qq{<a href="/manx/login?LOGO=1">Logout</a></div>};
	} else {
		my $redirloc = CGI::escape(url(-full => 1, -query => 1));
		print qq{<a href="/manx/login?redirect=$redirloc">Login</a></div>};
	}
	print qq{<div id="LOGO"><h1><span>Manx &ndash; a catalogue of online computer manuals</span></h1></div>};

	# Menu
	print qq{<div id="MENU">},
		qq{<a class="first" href="/manx/search">Search</a><span class="nodisp"> | </span>},
		qq{<a href="/manx/about">About</a><span class="nodisp"> | </span>},
		qq{<a href="/manx/help">Help</a>},
		qq{</div>\n};
}
