#!/usr/bin/perl -w

use strict;

use CGI qw(:cgi -no_xhtml);
use DBI;
use Encode;
use POSIX ();
use URI;
use Manx::DB;
use Manx::User;
use Manx::Utilities;

binmode STDOUT, ':utf8';

sub html_header($$);

my ($dbh, $smt, $sth, $rc, $rv, @rowary, $r);

my $SEARCHURL = '/manx/search';
my $DETAILSURL = '/manx/details';

my $DEFAULTNUMPERPAGE = 10;

my @errors;

$dbh = connectdb();
die $DBI::errstr if $DBI::err;

my $user = Manx::User::from_session($dbh, cookie('manxSession'));

if (!$user->{logged_in}) {
	$dbh->disconnect;
	# not logged in. use redirect param to get back here
	my $loc = url(-full => 1, -query => 1);
	my $log = URI->new_abs('/manx/login', $loc);
	$log->query_form(redirect => $loc);
	print header(-status => '303 login first', -location => $log, -type => 'text/plain', -charset => 'utf-8');
	exit;
}

@rowary = $dbh->selectrow_array('select confval from CONFIG where confkey="updated"');
my ($year, $mon, $mday, $hour, $min, $sec) = $rowary[0] =~ /(....)(..)(..)(..)(..)(..)/;
my $time = POSIX::mktime($sec, $min, $hour, $mday, $mon - 1, $year - 1900);
my $tlm = POSIX::strftime("%a, %d %b %Y %T GMT", gmtime($time));

my $param_q = decode("utf8", param('q')) if defined(param('q'));


print header(-charset => 'utf-8');
html_header($user->{logged_in}, $user->{username});

print qq{<div id="addformdiv"><form id="addform" action="add-pub2" method="get" name="f">};

print '<fieldset><legend id="plum">Essentials</legend><ul>';
print '<li><label for="company">Company:</label><select id="company" name="company">';

$sth = $dbh->prepare(q{select id,name,if(id=?,' selected','') as selected from COMPANY where display="Y" order by sort_name});
$sth->execute;
while ($r = $sth->fetchrow_hashref) {
	print '<option value="', html_encode($r->{id}), '"', $r->{selected}, '>', html_encode($r->{name}), "</option>\n";
}
print '</select></li>';

print '<li><label for="part">Part or order no.:</label><input type="text" id="part" name="part" value="', html_encode(param('part')), '"><button id="lkpt">Lookup</button><div id="partlist"></div></li>';

print '<li><label for="pubdate">Publication date:</label><input type="text" id="pubdate" name="pubdate" value="', html_encode(param('pubdate')), '" size="10" maxlength="10">',"</li>\n";

print '<li><label for="title">Title:</label><input type="text" id="title" name="title" value="', html_encode(param('title')), '" size="40"></li>';

print '</ul></fieldset>';

print '<fieldset><legend>Other bits</legend><ul>';

print '<li><label for="pt">Publication type:</label><select id="pt" name="pt">',
	'<option value="D"', (param('pt') eq 'D' ? ' selected' : ''), '>document</option>',
	'<option value="A"', (param('pt') eq 'A' ? ' selected' : ''), '>addendum</option>',
	'</select></li>';

print '<li><label for="altpart">Alternative part no.:</label><input type="text" id="altpart" name="altpart" value="', html_encode(param('altpart')), '"></li>';

print '<li><label for="revision">Revision:</label><input type="text" id="revision" name="revision" value="', html_encode(param('revision')), '"></li>';

print '<li><label for="keywords">Keywords:</label><input type="text" id="keywords" name="keywords" value="', html_encode(param('keywords')), '"></li>';

print '<li><label for="notes">Notes:</label><input type="text" id="notes" name="notes" value="', html_encode(param('notes')), '"></li>';

print '<li><label for="lang">Language(s):</label><input type="text" id="lang" name="lang" value="', html_encode(param('lang')), '"></li>';

print '</ul></fieldset>';

print '<input type="submit" name="opsave" value="Save">';
print '</form></div>';

print qq{<div class="navbot"><hr>Comments, queries or problems to &lt;$Manx::DB::admin_email&gt;</div></div></body></html>\n};

$dbh->disconnect() if $dbh;
exit;

sub html_header($$) {
	my ($logged_in, $username) = @_;

	print qq{<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n},
		qq{<html lang="en">\n<head>\n<title>Manx</title>\n},
		qq{<link rel="stylesheet" type="text/css" href="manx-style.css">\n},
		qq{<link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">\n},
		qq{<script type="text/javascript" src="jquery-1.3.2.min.js"></script>\n},
		'<script type="text/javascript" src="lookpart.js"></script>',
		qq{</head>\n};

	print qq{<body id="VT100-NET">\n};
	print qq{<div id="AUTH">}, html_encode($username), ' | ';
	if ($logged_in) {
		print qq{<a href="/manx/login?LOGO=1">Logout</a></div>};
	} else {
		my $redirloc = CGI::escape(url(-full => 1, -query => 1));
		print qq{<a href="/manx/login?redirect=$redirloc">Login</a></div>};
	}
	print qq{<div id="LOGO"><h1><span>Manx &ndash; a catalogue of online computer manuals</span></h1></div>};

	# Menu
	print qq{<div id="MENU">},
		qq{<a class="first" href="/manx/search">Search</a><span class="nodisp"> | </span>},
		qq{<a href="/manx/about">About</a><span class="nodisp"> | </span>},
		qq{<a href="/manx/help">Help</a>},
		qq{</div>\n};
}
