#!/usr/bin/perl -w

# 2006-05-07 Use UTF8DBI
# 2004-05-13 Changed servers
# 2004-02-13 From static HTML to script

use strict;

use CGI qw(:cgi -no_xhtml);
use DBI;
use POSIX ();
use Manx::DB;
use Manx::User;
use Manx::Utilities;

binmode STDOUT, ':utf8';

sub html_header($$);

my ($dbh, $smt, $sth, $rc, $rv, @rowary);

my $SEARCHURL = '/manx/search';

$dbh = connectdb();
die $DBI::errstr if $DBI::err;

my $user = Manx::User::from_session($dbh, cookie('manxSession'));

@rowary = $dbh->selectrow_array('select confval from CONFIG where confkey="updated"');
my ($year, $mon, $mday, $hour, $min, $sec) = $rowary[0] =~ /(....)(..)(..)(..)(..)(..)/;
my $time = POSIX::mktime($sec, $min, $hour, $mday, $mon - 1, $year - 1900);
my $tlm = POSIX::strftime("%a, %d %b %Y %T GMT", gmtime($time));

param('q', '') if !defined(param('q'));
param('cp', '1') if !defined(param('cp'));

print header('-last-modified' => $tlm, '-cache-control' => 'max-age=600', '-expires' => '+1h', '-charset' => 'utf-8');
html_header($user->{logged_in}, $user->{username});

print qq{<DIV CLASS="det"><h1>Help</h1>\n};
print qq{<p>To search, enter a word or words from the title of the manual },
	qq{you're looking for, or some letters or digits from the part number. },
	qq{Each word you search for must contain at least three letters (or },
	qq{you'd get loads of false hits from part numbers). When you're },
	qq{searching for part numbers, don't worry about the difference },
	qq{between '0' and 'O'; DEC frequently confused the two in part numbers, },
	qq{so they're treated the same when searching.</p>\n};
print qq{<p>The search results consist of pages showing ten manuals at a time. },
	qq{The results show the manual's part number, date of publication, },
	qq{title and status, which is either blank or some combination of },
	qq{"Online" and "Superseded". Superseded means that a manual has either },
	qq{been <em>revised</em> since this edition or it has been <em>replaced</em> },
	qq{completely. Superseded manuals might still be online, so this catalogue },
	qq{still links to them. The manual that superseded this one will normally },
	qq{be found in the same search results.</p>\n};
print qq{<p>The title of each manual will be a link if there is more information },
	qq{available. If the status is "Online", clicking the link will show you all },
	qq{the copies available. If the title is a link but the manual isn't shown as },
	qq{being online then at least the Table of Contents is available. This isn't },
	qq{too useful (or common) but if it appears that the manual contains },
	qq{information you would like, you can at least ask on appropriate newsgroups },
	qq{or mailing lists whether anyone has a copy.</p>\n};

print qq{<div class="navbot"><hr>Manx is no longer maintained</div></div></body></html>\n};

$dbh->disconnect() if $dbh;
exit;

sub html_header($$) {
	my ($logged_in, $username) = @_;

	print qq{<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n},
		qq{<html lang="en">\n<head>\n<title>Manx</title>\n},
		qq{<link rel="stylesheet" type="text/css" href="manx-style.css">\n},
		qq{<link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">\n};

	print qq{<body id="VT100-NET">\n};
	print qq{<div id="AUTH">}, html_encode($username), ' | ';
	if ($logged_in) {
		print qq{<a href="/manx/login?LOGO=1">Logout</a></div>};
	} else {
		my $redirloc = CGI::escape(url(-full => 1, -query => 1));
		print qq{<a href="/manx/login?redirect=$redirloc">Login</a></div>};
	}
	print qq{<div id="LOGO"><h1><span>Manx &ndash; a catalogue of online computer manuals</span></h1></div>};

	# Menu
	print qq{<div id="MENU">},
		qq{<a class="first" href="/manx/search">Search</a><span class="nodisp"> | </span>},
		qq{<a href="/manx/about">About</a><span class="nodisp"> | </span>},
		qq{<a class="on">Help</a>},
		qq{</div>\n};

}
